name: Prettier

on:
  pull_request:
    branches: [ "main" ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check frontend formatting
        working-directory: client
        run: npx prettier --check .

      - name: Check backend formatting
        working-directory: server
        run: npx prettier --check .